version: '3.8'
services:
  aiconsortium:
    build:
      context: ./aiconsortium
      dockerfile: Dockerfile
    ports:
      - '4173:4173'
    networks:
      - app-network

  aiconference:
    build:
      context: ./aiconference
      dockerfile: Dockerfile
    # remap internal 4173 → external 4174 so nginx can distinguish
    ports:
      - '4174:4173'
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - aiconsortium
      - aiconference
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
